Update: studiopkg 5.7 to fix pre-14.1

diff --git a/studiopkg/studiopkg-5.7/usr/sbin/studiopkg b/studiopkg/studiopkg-5.7/usr/sbin/studiopkg
--- a/studiopkg/studiopkg-5.7/usr/sbin/studiopkg
+++ b/studiopkg/studiopkg-5.7/usr/sbin/studiopkg
@@ -26,7 +26,7 @@
 init()
 {
     APPNAME="studiopkg"
-    VERSION="5.6b28"
+    VERSION="5.7b1"
     TMPROOT=$(mktemp -d -p /tmp $APPNAME-XXXXXX) || exit
     trap "cleanup" HUP INT ABRT QUIT SEGV TERM KILL PIPE STOP TSTP
   
@@ -168,7 +168,7 @@ $APPNAME --update, -u                      syncs with file server
 $APPNAME --upgrade <package>               upgrade package
 $APPNAME --upgrade-all                     upgrade all packages
 $APPNAME --queue, -q <package>             download and install queue
-$APPNAME --new, -n                         download and install new packages
+$APPNAME --new                             download and install new packages
 $APPNAME --latest, -l                      checks for latest version of $APPNAME
 $APPNAME --gpg, -g                         import the Studioware GPG key
 $APPNAME --help, -h                        help
@@ -178,7 +178,7 @@ Extra options:
 
 --no-gui    disables dialog and uses text input
 --yes       assumes yes to answers (also implies --no-gui)
---log       creates studiopkg.log in /tmp
+--log       creates studiopkg.log in current directory
 
 Files:
 
@@ -330,38 +330,66 @@ get_queue()
 
     cd $TMPROOT || cleanup
 
-    case "$1" in
-        'audio'|'video'|'photo'|'full'|'system')
-            curl -fs $SBSERVER/queues/$1.sqf > $QUEUE
-            ;;
+    if [ "$SWVERSION" = "14.1" ]; then
+        case "$1" in
+            'audio'|'video'|'photo'|'full'|'system')
+                curl -fs $SBSERVER/queues/$1.sqf > $QUEUE
+                ;;
 
-        *)
-            CAT=$(grep -i /$1.tar.gz$ $SLACKBUILDS | cut -d/ -f2-4)
-            APP=$(echo $CAT | cut -d/ -f3)
+            *)
+                CAT=$(grep -i /$1.tar.gz$ $SLACKBUILDS | cut -d/ -f2-4)
+                APP=$(echo $CAT | cut -d/ -f3)
 
-            if [ -n "$CAT" ]; then
-                curl -fs $SBSERVER/$CAT/$APP.sqf > $QUEUE
+                if [ -n "$CAT" ]; then
+                    curl -fs $SBSERVER/$CAT/$APP.sqf > $QUEUE
 
-                if [ $? != 0 ]; then
-                    echo "Queue $1.sqf not found."
-                    echo "Will try application directly."
-                    local_queue "$@"
-                fi
-            else
-                if [ ! -r $CWD/$1 ] && [ ! -r $1 ]; then
-                    echo "Queue $1 not found."
-                    cleanup
-                else
-                    if [ -r "$CWD/$1" ]; then
-                        cat $CWD/$1 > $QUEUE
-                    else
-                        cat $1 > $QUEUE
+                    if [ $? != 0 ]; then
+                        echo "Queue $1.sqf not found."
+                        echo "Will try application directly."
+                        local_queue "$@"
                     fi
+                else
+                    if [ ! -r $CWD/$1 ] && [ ! -r $1 ]; then
+                        echo "Queue $1 not found."
+                        cleanup
+                    else
+                        if [ -r "$CWD/$1" ]; then
+                            cat $CWD/$1 > $QUEUE
+                        else
+                            cat $1 > $QUEUE
+                        fi
 
+                    fi
                 fi
+                ;;
+        esac
+    else
+        curl -fs $SBSERVER/$1.sqf > $QUEUE
+        CAT=$(grep -i /$1.tar.gz$ $SLACKBUILDS | cut -d/ -f2-4)
+        APP=$(echo $CAT | cut -d/ -f3)
+
+        if [ -n "$CAT" ]; then
+            curl -fs $SBSERVER/$CAT/$APP.sqf > $QUEUE
+
+            if [ $? != 0 ]; then
+                echo "Queue $1.sqf not found."
+                echo "Will try application directly."
+                local_queue "$@"
             fi
-            ;;
-    esac
+        else
+            if [ ! -r $CWD/$1 ] && [ ! -r $1 ]; then
+                echo "Queue $1 not found."
+                cleanup
+            else
+                if [ -r "$CWD/$1" ]; then
+                    cat $CWD/$1 > $QUEUE
+                else
+                    cat $1 > $QUEUE
+                fi
+
+            fi
+        fi
+    fi
 
     list_pkgs
 }
@@ -549,17 +577,31 @@ list_pkgs()
 
     cat $TMPQ > $QUEUE
 
-    while read name
-    do
-        pkg=$(grep -i /$name-[^-]*-[^-]*-[^-]*txz$ $FILELIST | cut -d/ -f4)
+    if [ "$SWVERSION" = "14.1" ]; then
+        while read name
+        do
+            pkg=$(grep -i /$name-[^-]*-[^-]*-[^-]*txz$ $FILELIST | cut -d/ -f4)
 
-        if [ -n "$pkg" ]; then
-            LIST=$LIST" "$pkg" "$name" ""on "
-            PKGS=$pkg" "$PKGS
-        else
-            MISSING=$name" "$MISSING
-        fi
-    done < $QUEUE
+            if [ -n "$pkg" ]; then
+                LIST=$LIST" "$pkg" "$name" ""on "
+                PKGS=$pkg" "$PKGS
+            else
+                MISSING=$name" "$MISSING
+            fi
+        done < $QUEUE
+    else
+        while read name
+        do
+            pkg=$(grep -i /$name-[^-]*-[^-]*-[^-]*txz$ $FILELIST | cut -d/ -f3)
+
+            if [ -n "$pkg" ]; then
+                LIST=$LIST" "$pkg" "$name" ""on "
+                PKGS=$pkg" "$PKGS
+            else
+                MISSING=$name" "$MISSING
+            fi
+        done < $QUEUE
+    fi
 
     if [ -n "$MISSING" ]; then
         echo "The following are in the queue, but not in the server file list:"
